import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "@/styles/index.scss"
import Header from "@/components/Header";
import { QueryProvider } from "@/providers/QueryProvider";

const poppins = Poppins({ variable: "--font-poppins", subsets: ['latin'], weight: ['300', '400', '500', '600', '700'], display: "swap" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        rel: "icon",
        type: "image/svg",
        url: "/favicon.svg"
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
